### ISSUE TITLE
"Up" non-zero return value

### ISSUE THREAD

**Issue by ertanden** [balmasi/migrate-mongoose#15]
When I run "migrate up" and there are no migrations to run the program returns a non-zero value, which usually indicates an "error".

I think, it should return 0 instead of an error when there are no migrations to run.

**Comment by balmasi** [comment]
@ertanden that's a good insight. I guess I'll have to separate the return value between the CLI usage and the API usage

**Comment by river-jade** [comment]
Here's a pull-request: https://github.com/balmasi/migrate-mongoose/pull/20

**Comment by rkmax** [comment]
Hi Guys did you plan to merge the #20 I want to use this on my CI, currently my workaround is:

    "migrate": "migrate up || exit 0"

**Comment by gunar** [comment]
@rkmax The problem with that is that it won't know when the migration actually failed.

**Comment by keenahn** [comment]
<img width="657" alt="screen shot 2017-09-20 at 23 29 42" src="https://user-images.githubusercontent.com/283603/30655615-bd3e7808-9e5b-11e7-84ce-c68c262ecd7b.png">

Don't hold your breath, looks like this project is abandoned

**Comment by balmasi** [comment]
Fixed in 4.0.0 thank you, everyone for your contributions!

**Comment by Parnswir** [comment]
This still seems to be broken. I have this in my package.json:
```
"dependencies": {
  "migrate-mongoose": "^4.0.0"
},
"scripts": {
  "migration": "migrate"
},
```
So that I can run `npm run migration up`, etc. However, `up` still fails with exit status 1 if there are no migrations:

```
> npm run migration up

Synchronizing database with file system migrations...
There are no pending migrations.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mypackage@1.0.0 migration: `migrate "up"`
npm ERR! Exit status 1
```

Am I missing something here?
