### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by BastienAr** [balmasi/migrate-mongoose#9]
I probably misundestood something about your module, because this kind of code

``` javascript
'use strict';

var User = require('../models/user.js');

/**
 * Make any changes you need to make to the database here
 */
exports.up = function up(done) {
    User = this('User');
    var user = new User({
        username: "foo"
    });
    user.save()
        .then(function(response) {
            console.log(response);
            done();
        })
        .catch(function(err) {
            console.log(err);
            done(err);
        });
};
```

seems to block on the call to mongoose save. Did I miss something about how thinks should be done ?

**Comment by balmasi** [comment]
@BastienAr  The answer depends on how you registered your model in `../models/user`

if you did `mongoose.model('user', UserSchema)`, then you'd do `this('user')` in your code, not `this('User')`

The migration framework opens its own connection to mongoose, and exposes `mongoose.model` as `this`.

You can try what I mentioned above, but I recommend just doing the import as you're doing and not assigning it from `this('whatever')`

You can also do away with the callbacks and just `return user.save().then()...` because we have promise support :)

Let me know how that works out, or if you can suggest a way to improve the way it's set up so it's less confusing. Do we need to change the architecture? More documentation explaining something specific? An example? 

Cheers

**Comment by gt6796c** [comment]
I've just run into this as well. I think it is due to commit 02e6f018ca9d71e3082b1c819c438630c7ba0b32. 

Mongoose's behavior is to hang if there is not a connection when you tell it to do something. If your model module just does the standard `User = mongoose.model('User',UserSchema)` then it gets attached to the first connection for mongoose. Later on when you call `save()` it is against this connection that has never been initialized (since migrate-mongoose creates and initializes its own connection.) If you add something like this
```
var mongoose = require('mongoose');
if (mongoose.connection.readyState != mongoose.STATE_OPEN)
{
    mongoose.connect(process.env.MONGODB_URI); // or wherever you're getting this from
}
var User = require('../models/user.js').User;
```

to the beginning of each migration, it'll make sure it is connected. I don't know if there is a better place to put such code, but this got me past this problem after struggling with it for a few hours. (I put it in the migration since I didn't want to clutter the app's code since the app can always assume a connection is there.)

I'm not sure what the reasoning of the prior commit was, but the docs should probably get updated to alert users because it sure is a non-obvious behavior.

**Comment by jay-at-avido** [comment]
@gt6796c  thanks for sharing your solution.
I can't get direct model access to work so this also seem to have broken by recent commits, I have created an issue about it

**Comment by jay-at-avido** [comment]
https://github.com/balmasi/migrate-mongoose/issues/13

**Comment by balmasi** [comment]
This should be fixed in `> 2.1.0`

**Comment by paventuri** [comment]
This is still an issue for me. I'm using 3.2.2. 

I have to do @gt6796c suggested.

```
var mongoose = require('mongoose');
if (mongoose.connection.readyState != mongoose.STATE_OPEN)
{
    mongoose.connect(process.env.MONGODB_URI); // or wherever you're getting this from
}
var User = require('../models/user.js').User;
```

Any suggestion to use the default connection instead of opening a new one?
